# Generated by Django 2.2.12 on 2021-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20211006_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewimage',
            name='original',
            field=models.FileField(max_length=255, upload_to='review-media/', verbose_name='Original'),
        ),
    ]
