# Generated by Django 2.2.12 on 2021-10-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_timeslotconfiguration_index'),
        ('reviews', '0008_auto_20211006_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='order.Line'),
        ),
    ]
