# Generated by Django 2.2.12 on 2021-10-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_productreview_order_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-total_votes', '-delta_votes')},
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
    ]
