# Generated by Django 2.2.12 on 2021-10-07 12:09

from django.db import migrations, models
import oscar.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20211007_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[oscar.core.validators.non_whitespace], verbose_name='Title'),
        ),
    ]
