# Generated by Django 2.2.12 on 2021-10-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20211007_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_fake_review',
            field=models.BooleanField(default=False),
        ),
    ]
