# Generated by Django 2.2.12 on 2021-11-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20211108_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
    ]
