# Generated by Django 2.1.15 on 2021-02-03 12:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delhivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelhiveryResponse',
            fields=[
                ('pincode', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('response', jsonfield.fields.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
