# Generated by Django 2.2.12 on 2020-06-24 04:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion

from apps.availability.migration_operations import populate_pincode_reverse, populate_pincode


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('poly', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PincodePartnerThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincode_mappings', to='partner.Partner')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_mappings', to='availability.PinCode')),
            ],
        ),
        migrations.AddField(
            model_name='pincode',
            name='partners',
            field=models.ManyToManyField(through='availability.PincodePartnerThroughModel', to='partner.Partner'),
        ),
        migrations.RunPython(
            code=populate_pincode,
            reverse_code=populate_pincode_reverse,
            atomic=None
        ),
    ]
