# Generated by Django 2.2.12 on 2020-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='partners',
            field=models.ManyToManyField(related_name='pincodes', through='availability.PincodePartnerThroughModel', to='partner.Partner'),
        ),
    ]
