# Generated by Django 2.2.12 on 2020-06-26 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('availability', '0002_auto_20200625_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=32)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pincode_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
