# Generated by Django 2.2.12 on 2021-06-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='zones',
            name='pincode',
            field=models.ManyToManyField(to='availability.PinCode'),
        ),
    ]
