# Generated by Django 2.2.12 on 2021-11-09 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_zones_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='zones',
            name='is_default_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zones',
            name='pincode',
            field=models.ManyToManyField(blank=True, null=True, to='availability.PinCode'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='zone',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
