# Generated by Django 2.2.12 on 2020-06-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_pincodelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PincodeLog',
        ),
    ]
