
class AbstractFacade(object):

    session = None

    def __init__(self):
        """
        Initializing Function. Set all api Keys here or create a client connection with name 'self.session'

        """

    @staticmethod
    def get_friendly_decline_message(error):
        return 'The transaction was declined by your bank - please check your bankcard details and try again'

    @staticmethod
    def get_friendly_error_message(error):
        return 'An error occurred when communicating with the payment gateway.'

    def charge(self, order_number, total, token, currency='INR', description=None, metadata=None, **kwargs):
        """
        'Facade.charge()' Function charges the required payment~
            order_number: str =>  Reference number we should pass to provider.
            total: float =>  Total Amount (inclusive of all taxs) to be charged for order.
            token: string =>  Token generated by third party authentication Mechanism,
                             which is needed for triggering transaction.
            currency: string => Currency code. eg: INR
            description: string => Description shown along with the transaction.
            metadata: dict => Description shown along with the transaction.

        """
