# Generated by Django 2.2.12 on 2021-06-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_squashed_0008_auto_20210429_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Just to take the value as input, this will not used for any calculation other than calculation `price_excl_tax` field', max_digits=12, null=True, verbose_name='Selling Price (incl. tax)'),
        ),
    ]
