# Generated by Django 2.2.12 on 2020-07-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_partner_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='location',
        ),
    ]
