# Generated by Django 2.2.12 on 2021-04-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_remove_partner_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='price_excl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Selling Price (excl. tax)'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='price_retail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='M.R.P. (retail)'),
        ),
    ]
