# Generated by Django 2.2.12 on 2020-08-03 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_line_refunded_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_cancelled', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('delivery_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_consignments', to='logistics.DeliveryTrip')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Line')),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('delivery_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_consignments', to='logistics.DeliveryTrip')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
