# Generated by Django 2.2.12 on 2020-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytrip',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='deliverytrip',
            name='route',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
