# Generated by Django 2.2.12 on 2020-09-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_deliverytrip_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentdelivery',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='deliverytrip',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='deliverytrip',
            name='is_active',
        ),
        migrations.AddField(
            model_name='consignmentdelivery',
            name='status',
            field=models.CharField(choices=[('On Trip', 'On Trip'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Yet to Start', 'Yet to Start')], default='Yet to Start', max_length=20),
        ),
        migrations.AddField(
            model_name='consignmentreturn',
            name='status',
            field=models.CharField(choices=[('On Trip', 'On Trip'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Yet to Start', 'Yet to Start')], default='Yet to Start', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverytrip',
            name='status',
            field=models.CharField(choices=[('On Trip', 'On Trip'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Yet to Start', 'Yet to Start')], default='Yet to Start', max_length=20),
        ),
    ]
