# Generated by Django 2.2.12 on 2020-09-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_deliverytrip_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytrip',
            name='trip_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
