# Generated by Django 2.2.12 on 2020-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_deliverytrip_trip_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentdelivery',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignmentreturn',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytrip',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
