# Generated by Django 2.2.12 on 2021-06-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_source_is_active'),
        ('logistics', '0008_failedrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedrefund',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.Source'),
        ),
    ]
