# Generated by Django 2.2.12 on 2021-06-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_failedrefund_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.PositiveIntegerField(default=True)),
                ('max_orders', models.PositiveIntegerField(default=20, help_text='Max no of orders which can be delivered during trip, 999 for unlimited!')),
            ],
        ),
        migrations.CreateModel(
            name='SlotObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_out_for_delivery', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.Slot')),
            ],
        ),
    ]
