# Generated by Django 2.2.12 on 2020-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200807_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.ImageField(blank=True, help_text='Driving License, ID Card etc... specially used for Delivery Boys.', null=True, upload_to='user_documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pictures'),
        ),
    ]
