# Generated by Django 2.2.12 on 2020-09-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200921_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_id',
            field=models.TextField(blank=True, help_text='Applicable only to System Employees Accounts', null=True),
        ),
    ]
