# Generated by Django 2.2.12 on 2020-06-29 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_gstnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GSTNumber',
            new_name='UserProfile',
        ),
    ]
