# Generated by Django 2.2.12 on 2020-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.TextField(blank=True, help_text='Applicable only to System Employees Accounts', null=True, verbose_name='Employee ID'),
        ),
    ]
