# Generated by Django 2.2.12 on 2020-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_location_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
