# Generated by Django 2.2.12 on 2020-09-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200921_1527'),
        ('users', '0004_auto_20200922_1911'),
    ]

    operations = [
    ]
