# Generated by Django 2.2.12 on 2020-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200722_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery_boy',
            field=models.BooleanField(default=False),
        ),
    ]
