# Generated by Django 2.2.12 on 2021-06-28 10:25

import apps.users.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20200923_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pincode',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[apps.users.models.pincode_required]),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[apps.users.models.location_required]),
        ),
    ]
