# Generated by Django 2.2.12 on 2020-06-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200630_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
