# Generated by Django 2.2.12 on 2020-07-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
