# Generated by Django 2.2.12 on 2020-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20200525_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='documents',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True, verbose_name='Shipping Charge'),
        ),
    ]
