# Generated by Django 2.2.12 on 2020-05-29 06:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations

from lib import custom_migrate


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20200525_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='catalogue_p_search_618b3f_gin'),
        ),
        custom_migrate.IndexAfterSearchMigration(
            model_name='product',
        )
    ]
