# Generated by Django 2.2.12 on 2020-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20200529_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='effective_mrp',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Retail Price Cached'),
        ),
        migrations.AddField(
            model_name='product',
            name='effective_retail_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Retail Price Cached'),
        ),
    ]
