# Generated by Django 2.2.12 on 2020-06-04 06:15

from django.db import migrations, models

from lib import custom_migrate


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20200529_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='effective_mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='effective_retail_price',
        ),
        migrations.AddField(
            model_name='product',
            name='effective_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Effective Retail Price.'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Effective Retail Price.'),
        ),
        custom_migrate.PopulatePriceAfterMigration(
            model_name='product',
        )

    ]
