# Generated by Django 2.2.12 on 2020-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20200604_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_varying',
            field=models.BooleanField(default=False, verbose_name='Is Varying For Child'),
        ),
    ]
