# Generated by Django 2.2.12 on 2020-06-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_productattribute_is_varying'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=64)),
                ('usage', models.IntegerField(default=1)),
                ('rank', models.FloatField(default=0.0)),
                ('hits', models.IntegerField(default=0)),
                ('product_class', models.ForeignKey(blank=True, help_text='Choose what type of product this is', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_searches', to='catalogue.ProductClass', verbose_name='Product type')),
            ],
        ),
    ]
