# Generated by Django 2.2.12 on 2020-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_searchresponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresponses',
            name='rank',
            field=models.FloatField(default=0.0, help_text='Ranking of term'),
        ),
        migrations.AlterField(
            model_name='searchresponses',
            name='usage',
            field=models.IntegerField(default=1, help_text='Count of Products Which Matches this query on last calculation'),
        ),
    ]
