# Generated by Django 2.2.12 on 2020-06-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20200611_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Retail Price.'),
        ),
    ]
