# Generated by Django 2.2.12 on 2020-07-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20200701_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_product_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='care_instructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_redressal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='merchant_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='returns_and_cancellations',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_and_installation',
        ),
    ]
