# Generated by Django 2.2.12 on 2021-04-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_cartspecificproductrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartSpecificProductRecommendation',
        ),
    ]
