# Generated by Django 2.2.12 on 2021-04-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_auto_20200807_1256'),
        ('catalogue', '0032_delete_cartspecificproductrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSpecificProductRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Determines order of the products. A product with a higher value will appear before one with a lower ranking.', verbose_name='Ranking')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendations', to='basket.Basket', verbose_name='Cart')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Recommended product')),
            ],
            options={
                'verbose_name': 'Basket Based recommendation',
                'verbose_name_plural': 'Basket Based recomendations',
                'ordering': ['primary', '-ranking'],
                'unique_together': {('primary', 'recommendation')},
            },
        ),
    ]
