# Generated by Django 2.2.12 on 2021-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20210611_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exclude_in_listing',
            field=models.BooleanField(default=False),
        ),
    ]
