# Generated by Django 2.2.12 on 2021-10-06 13:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_auto_20210817_1632'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('browsable', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Count of Rating'),
        ),
    ]
