# Generated by Django 2.2.12 on 2021-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_auto_20211006_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Count of Review'),
        ),
    ]
