# Generated by Django 2.2.12 on 2021-10-11 09:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20211011_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Color'),
        ),
    ]
