# Generated by Django 2.2.12 on 2021-10-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_productattributevalue_value_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is Visible in Details'),
        ),
    ]
