# Generated by Django 2.2.12 on 2021-10-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_productattributevalue_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='crossselling',
            field=models.ManyToManyField(blank=True, help_text='These are products that are recommended to accompany the main product.', related_name='crosssell_with', to='catalogue.Product', verbose_name='Cross Selling products'),
        ),
    ]
