# Generated by Django 2.2.12 on 2021-10-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_auto_20211028_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.ProductClass'),
        ),
    ]
