# Generated by Django 2.2.12 on 2021-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_auto_20211102_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
