# Generated by Django 2.2.12 on 2021-11-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_auto_20211102_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_tags',
        ),
        migrations.AddField(
            model_name='product',
            name='search_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
