# Generated by Django 2.2.12 on 2021-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0052_auto_20211104_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='is_visible_in_filter',
            field=models.BooleanField(default=True, verbose_name='Is Visible in Filter'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='is_varying',
            field=models.BooleanField(default=False, verbose_name='Is Varying For Child Shown detail page child switcher.'),
        ),
    ]
