# Generated by Django 2.2.12 on 2021-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_auto_20211104_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='is_visible_in_filter',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_visible_in_filter',
            field=models.BooleanField(default=True, verbose_name='Is Visible in Filter'),
        ),
    ]
