# Generated by Django 2.2.12 on 2021-11-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_auto_20211104_2352'),
        ('catalogue', '0053_auto_20211105_1003'),
    ]

    operations = [
    ]
