# Generated by Django 2.2.12 on 2021-11-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_productattributevalue_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='is_varying',
            field=models.BooleanField(default=False, help_text='Is Varying for child? Will be shown detail page child switcher', verbose_name='Is Varying.'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='is_visible_in_filter',
            field=models.BooleanField(default=True, help_text='Do we need to show this attribute at filter?', verbose_name='Is Visible in Filter'),
        ),
    ]
