# Generated by Django 2.2.12 on 2021-11-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_auto_20211106_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_visible_in_detail_page',
            field=models.BooleanField(default=True, help_text='Do we need to show this attribute detail page?', verbose_name='Is Visible in Detail page'),
        ),
    ]
