# Generated by Django 2.2.12 on 2021-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_productattribute_is_visible_in_detail_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='order_in_detail_page',
            field=models.PositiveSmallIntegerField(default=20, help_text='order 1 will show at top.', verbose_name='Display order'),
        ),
    ]
