# Generated by Django 2.2.12 on 2021-11-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0059_productattribute_order_in_detail_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wordpress_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wordpress_product_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
