# Generated by Django 2.2.12 on 2021-11-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0062_category_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_search_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
