# Generated by Django 2.2.12 on 2022-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0063_product_custom_search_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wordpress_product_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wordpress_product_text',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
