# Generated by Django 2.2.12 on 2022-04-05 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0064_auto_20220308_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_vector', models.CharField(blank=True, max_length=100, null=True)),
                ('y_vector', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product360Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product360/')),
                ('product', models.ManyToManyField(blank=True, null=True, through='catalogue.ImageVector', to='catalogue.Product')),
            ],
        ),
        migrations.AddField(
            model_name='imagevector',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product360Image'),
        ),
        migrations.AddField(
            model_name='imagevector',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product'),
        ),
    ]
