# Generated by Django 2.2.12 on 2021-07-01 04:51

import apps.order.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_squashed_0013_auto_20210510_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Delivery Time Starting of this slot')),
                ('end_time', models.TimeField(help_text='(Expected) Delivery Time Ending of this slot')),
                ('deliverable_no_of_orders', models.PositiveSmallIntegerField(help_text='No of Orders you can handle in this Slot! Each order will be at each location and will have diff size and no of items.')),
                ('orders_prepare_delay', models.PositiveSmallIntegerField(help_text='This field specifies the time you want to prepare the orders! if your slot is 5PM-7PM, and orders_prepare_delay=180minutes, Any orders placed after 2PM will not show this slot!')),
                ('week_day_code', models.PositiveSmallIntegerField(choices=[(1, 'SUNDAY'), (2, 'MONDAY'), (3, 'TUESDAY'), (4, 'WEDNESDAY'), (5, 'THURSDAY'), (6, 'FRIDAY'), (7, 'SATURDAY')], default=1, validators=[apps.order.models.length_in_weeks])),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.TextField(help_text='Text Representation of configuration')),
                ('start_date', models.DateField(help_text='Delivery Starting Date')),
                ('index', models.PositiveIntegerField(help_text='Slot Index')),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.TimeSlotConfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.TimeSlot'),
        ),
    ]
