# Generated by Django 2.2.12 on 2021-07-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210701_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeslotconfiguration',
            name='orders_prepare_delay',
            field=models.PositiveSmallIntegerField(help_text='In Minutes. This field specifies the time you want to prepare the orders! if your slot is 5PM-7PM, and orders_prepare_delay=180, (180 minutes) Any orders placed after 2PM will not show this slot!'),
        ),
    ]
