# Generated by Django 2.2.12 on 2021-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210705_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslotconfiguration',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
