# Generated by Django 2.2.12 on 2021-11-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delhivery', '0002_delhiveryresponse'),
        ('order', '0005_timeslotconfiguration_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delhivery_consignments', to='delhivery.RequestPickUp'),
        ),
    ]
