# Generated by Django 2.2.12 on 2021-11-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waybill',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
