# Generated by Django 2.2.12 on 2020-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='refunded_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
