# Generated by Django 2.2.12 on 2022-04-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_waybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='index',
            field=models.BigIntegerField(help_text='Slot Index'),
        ),
    ]
