# Generated by Django 2.2.12 on 2020-09-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200807_1443'),
        ('order', '0008_line_refunded_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Location'),
        ),
    ]
