# Generated by Django 2.2.12 on 2021-01-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_shippingaddress_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
