# Generated by Django 2.2.12 on 2021-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_shippingaddress_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivered',
            field=models.DateTimeField(blank=True, help_text='Date of Consignment Delivery', null=True),
        ),
    ]
