# Generated by Django 2.2.12 on 2021-05-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_useraddress_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='line5',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='House No'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Apartment Name'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='line3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Details'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='line4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Landmark'),
        ),
    ]
