# Generated by Django 2.2.12 on 2020-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20200616_0918'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open - currently active'), ('Merged', 'Merged - superceded by another basket'), ('Saved', 'Saved - for items to be purchased later'), ('Frozen', 'Frozen - the basket cannot be modified'), ('Submitted', 'Submitted - has been ordered at the checkout')], default='Open', max_length=128, verbose_name='Status'),
        ),
    ]
