# Generated by Django 2.2.12 on 2020-07-15 07:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_auto_20200710_1940'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
                ('buy_now', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Buy Now', 'Buy Now'), ('Open', 'Open - currently active'), ('Merged', 'Merged - superceded by another basket'), ('Saved', 'Saved - for items to be purchased later'), ('Frozen', 'Frozen - the basket cannot be modified'), ('Submitted', 'Submitted - has been ordered at the checkout')], default='Open', max_length=128, verbose_name='Status'),
        ),
    ]
