# Generated by Django 2.2.12 on 2021-03-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_remove_partner_location'),
        ('custom', '0006_homepagemegabanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbanner',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner'),
        ),
    ]
