# Generated by Django 2.2.12 on 2021-03-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20181115_1953'),
        ('custom', '0007_offerbanner_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=10, help_text='Larger the number, higher will be the priority')),
                ('title', models.CharField(max_length=256, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(upload_to='offer-banners/')),
                ('type', models.CharField(choices=[('Slider', 'Slider'), ('Full Screen', 'Full Screen')], default='Slider', max_length=20)),
                ('product_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Range')),
            ],
            options={
                'ordering': ('-position', 'id'),
                'abstract': False,
            },
        ),
    ]
