# Generated by Django 2.2.12 on 2021-04-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0009_abstractinappbanner_inappfullscreenbanner_inappsliderbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractInAppBanner',
        ),
        migrations.CreateModel(
            name='AbstractInAppBanner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('custom.inappbanner',),
        ),
    ]
