# Generated by Django 2.2.12 on 2021-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0010_auto_20210429_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnreason',
            name='reason_type',
            field=models.CharField(choices=[('return', 'Return'), ('cancel', 'Cancel')], default='return', max_length=256),
        ),
    ]
