# Generated by Django 2.2.12 on 2021-06-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0012_siteconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='delivery_charge_for_express_delivery',
            new_name='DELIVERY_CHARGE_FOR_EXPRESS_DELIVERY',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='delivery_charge_for_free_delivery',
            new_name='DELIVERY_CHARGE_FOR_FREE_DELIVERY',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='min_basket_amount_for_free_delivery',
            new_name='MIN_BASKET_AMOUNT_FOR_FREE_DELIVERY',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='DEFAULT_PERIOD_OF_PICKUP',
            field=models.DurationField(default='01 00:00:00', help_text='Default Period of Return !'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='DEFAULT_PERIOD_OF_RETURN',
            field=models.DurationField(default='03:00:00', help_text='Default Period of Return !'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='EXPECTED_OUT_FOR_DELIVERY_DELAY',
            field=models.DurationField(default='03:00:00', help_text='Expected delay between End Slot, and Delivery Boy moving out for free delivery!'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='EXPECTED_OUT_FOR_DELIVERY_DELAY_IN_EXPRESS_DELIVERY',
            field=models.DurationField(default='03:00:00', help_text='Expected delay between End Slot, and Delivery Boy moving out for express delivery !'),
        ),
    ]
