# Generated by Django 2.2.12 on 2021-07-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0014_auto_20210617_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='DEFAULT_PERIOD_OF_PICKUP',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='DEFAULT_PERIOD_OF_RETURN',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='DELIVERY_CHARGE_FOR_EXPRESS_DELIVERY',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='EXPECTED_OUT_FOR_DELIVERY_DELAY',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='EXPECTED_OUT_FOR_DELIVERY_DELAY_IN_EXPRESS_DELIVERY',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='period_of_return',
        ),
    ]
