# Generated by Django 2.2.12 on 2021-07-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0015_auto_20210701_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='DEFAULT_PERIOD_OF_PICKUP',
            field=models.PositiveIntegerField(default=1440, help_text='Default Period of Return (in minutes)!'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='DEFAULT_PERIOD_OF_RETURN',
            field=models.PositiveIntegerField(default=180, help_text='Default Period of Return (in minutes)!'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='DELIVERY_CHARGE_FOR_EXPRESS_DELIVERY',
            field=models.PositiveSmallIntegerField(default=180, help_text='EXPRESS DELIVERY CHARGE'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='EXPECTED_OUT_FOR_DELIVERY_DELAY',
            field=models.PositiveSmallIntegerField(default=180, help_text='Expected delay between End Slot, and Delivery Boy moving out for free delivery (in minutes)!'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='EXPECTED_OUT_FOR_DELIVERY_DELAY_IN_EXPRESS_DELIVERY',
            field=models.PositiveIntegerField(default=180, help_text='Expected delay between End Slot, and Delivery Boy moving out for express delivery(in minutes)!'),
        ),
    ]
