# Generated by Django 2.2.12 on 2021-08-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0018_auto_20210812_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=10, help_text='Larger the number, higher will be the priority')),
                ('title', models.CharField(max_length=256, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(help_text="Recommended : '1920x690'", upload_to='home-banner-images')),
                ('social_media_url', models.URLField()),
            ],
            options={
                'ordering': ('-position', 'id'),
                'abstract': False,
            },
        ),
    ]
