# Generated by Django 2.2.12 on 2021-11-05 04:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0019_socialmediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_seo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_seo_footer',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_seo_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_seo_image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_seo_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
