# Generated by Django 2.2.12 on 2021-11-07 11:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0020_auto_20211105_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='home_seo_footer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
