# Generated by Django 2.2.12 on 2021-12-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0021_auto_20211107_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='sync_google_sheet_id',
            field=models.CharField(default='1WIeWBr4rka0SDO32VOcDw_N8tttySqC4YjC0Gh9Zr3Q', max_length=256),
        ),
    ]
