# Generated by Django 2.2.12 on 2022-04-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0023_auto_20220318_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brochures/')),
                ('type', models.CharField(blank=True, choices=[('brochure', 'Brochure'), ('catelogue', 'Catelogue')], max_length=50, null=True)),
            ],
        ),
    ]
