# Generated by Django 2.2.12 on 2022-05-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0026_album_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochure',
            name='type',
            field=models.CharField(blank=True, choices=[('brochure', 'Brochure'), ('catalogue', 'Catalogue')], max_length=50, null=True),
        ),
    ]
