from django.conf import settings

PIN_CODE = 'pincode'
ZONES = 'zones'
SUPPORTING_MODES = {PIN_CODE, ZONES}


# DETERMINE APP SHOULD WORK ON WHICH ALL MODES.
AVAILABILITY_MODES = getattr(settings, 'AVAILABILITY_MODES', [ZONES, ])

assert not set(AVAILABILITY_MODES).difference(SUPPORTING_MODES), f"Currently supporting only {SUPPORTING_MODES} modes"

PIN_CODE_MODE__ENABLED = PIN_CODE in AVAILABILITY_MODES
ZONE_MODE__ENABLED = ZONES in AVAILABILITY_MODES


# used only if PIN_CODE_MODE__ENABLED
ALLOW_CHOOSE_COUNTRY_FROM_DASHBOARD = getattr(settings, 'ALLOW_CHOOSE_COUNTRY_FROM_STATE', False)
ALLOW_CHOOSE_COUNTRY_FROM_STATE = getattr(settings, 'ALLOW_CHOOSE_COUNTRY_FROM_STATE', True)
LOAD_INITIAL_COUNTRIES = getattr(settings, 'FN_LOAD_PINCODE_FOR_USER', [])
FN_LOAD_PINCODE_FOR_USER = getattr(settings, 'FN_LOAD_PINCODE_FOR_USER', None)


# used only if ZONE_MODE__ENABLED


