# Generated by Django 2.2.12 on 2020-07-31 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_auto_20181115_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateWayResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment Transaction ID', models.CharField(max_length=128)),
                ('transaction_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Refund', 'Refund'), ('Others', 'Others')], default='Purchase', max_length=128)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Source')),
            ],
        ),
    ]
