# Generated by Django 2.2.12 on 2020-07-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentgatewayresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayresponse',
            name='amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
