# Generated by Django 2.2.12 on 2020-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymentgatewayresponse_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayresponse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
