# Generated by Django 2.2.12 on 2020-07-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymentgatewayresponse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayresponse',
            name='payment_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
