# Generated by Django 2.2.12 on 2020-07-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paymentgatewayresponse_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayresponse',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.PaymentGateWayResponse'),
        ),
    ]
