# Generated by Django 2.2.12 on 2020-08-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_line_refunded_quantity'),
        ('payment', '0009_paymentgatewayresponse_parent_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='COD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField()),
                ('cod_accepted', models.BooleanField(default=False)),
                ('cod_transferred', models.BooleanField(default=False)),
                ('amount_received_on', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cods', to='order.Order')),
            ],
        ),
    ]
