# Generated by Django 2.2.12 on 2020-08-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cods', to='order.Order'),
        ),
        migrations.CreateModel(
            name='CODRepayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('amount_received_on', models.DateTimeField()),
                ('cod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cod_refunds', to='payment.COD')),
            ],
        ),
    ]
