# Generated by Django 2.2.12 on 2020-08-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20200801_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cod', to='order.Order'),
        ),
    ]
