# Generated by Django 2.2.12 on 2020-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20200801_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codrepayments',
            name='amount_received_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
