# Generated by Django 2.2.12 on 2020-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20200801_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='amount_received_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
