# Generated by Django 2.2.12 on 2020-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20200801_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codrepayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
