# Generated by Django 2.2.12 on 2020-08-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20200801_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgatewayresponse',
            name='payee',
        ),
    ]
