# Generated by Django 2.2.12 on 2020-09-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_remove_paymentgatewayresponse_payee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgatewayresponse',
            name='Payment Transaction ID',
        ),
        migrations.AddField(
            model_name='paymentgatewayresponse',
            name='transaction_id',
            field=models.CharField(max_length=128, null=True, verbose_name='Payment Transaction ID'),
        ),
    ]
