# Generated by Django 2.2.12 on 2020-09-29 11:32

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20200910_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayresponse',
            name='response',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
