# Generated by Django 2.2.12 on 2020-10-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_paymentgatewayresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
