# Generated by Django 2.2.12 on 2022-03-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_waybill'),
        ('payment', '0019_source_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayresponse',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
