# Generated by Django 2.2.12 on 2022-03-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_paymentgatewayresponse_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayresponse',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.Source'),
        ),
    ]
